/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;
import Class.Model_BarangKeluar;
import Class.Model_DetBarangKeluar;
import Class.Model_Barang;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author asus
 */
public class barang_Keluar extends javax.swing.JPanel {
    
    private Model_BarangKeluar modelBarangKeluar;
    private Model_DetBarangKeluar modelDetBarangKeluar;
    private DefaultTableModel tabelModelBarangKeluar;
    private DefaultTableModel tabelModelDetail;
    private TableRowSorter<DefaultTableModel> sorter;
    
    private barang_Keluar formPanel;
  
  
    /**
     * Creates new form barang_Keluar
     */
    public barang_Keluar() {
        initComponents();
        
        modelBarangKeluar = new Model_BarangKeluar();
        modelDetBarangKeluar = new Model_DetBarangKeluar();
        initTabelBarangKeluar();
        initTabelDetail();
        loadDataBarangKeluar();
        setupSearchFilter();
        setupTableListeners();
        setupButtonListeners();
        
        showPanelBarangKeluar();
        
    }
    private void setupButtonListeners(){
     btnHapus2.addActionListener(e -> hapusDetailBarangKeluar());}
    
    private void showPanelBarangKeluar(){}
    private void showPanelDetail(){}
    private void initTabelBarangKeluar(){}
    private void loadDataBarangKeluar(){}
    private void initTabelDetail(){}
    private void loadDetailBarangKeluar(){}
    private String getNamaBarang(String kodeBarang){
        return "";    
    }
    private void setupTableListeners(){}
    private void setupSearchFilter(){}
    private void tambahBarangKeluar(){}
    private void hapusBarangKeluar(){}
    private void ubahBarangKeluar(){}
    private void tambahDetailBarangKeluar(){}
    private void hitungSubtotal(){}
    private void updateTotalBarangKeluar(){}
    private void hapusDetailBarangKeluar(){}
    
   
    
           
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        barangKeluar1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblBarangKeluar = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtCari7 = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        detBarangKeluar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnTambah2 = new javax.swing.JButton();
        btnHapus2 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblBK = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txtCari6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblDetailBarangKeluar = new javax.swing.JTable();
        btnCetak7 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel15.setText("Data Barang Keluar");

        btnTambah.setBackground(new java.awt.Color(153, 255, 0));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(153, 255, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblBarangKeluar.setBackground(new java.awt.Color(204, 255, 204));
        tblBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangKeluarMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblBarangKeluar);

        txtCari7.setText("Pencarian");
        txtCari7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCari7txtCari2ActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(153, 255, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barangKeluar1Layout = new javax.swing.GroupLayout(barangKeluar1);
        barangKeluar1.setLayout(barangKeluar1Layout);
        barangKeluar1Layout.setHorizontalGroup(
            barangKeluar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangKeluar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barangKeluar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barangKeluar1Layout.createSequentialGroup()
                        .addGroup(barangKeluar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(barangKeluar1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel16))
                            .addGroup(barangKeluar1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(252, 252, 252)
                                .addComponent(txtCari7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(barangKeluar1Layout.createSequentialGroup()
                        .addGroup(barangKeluar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(barangKeluar1Layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        barangKeluar1Layout.setVerticalGroup(
            barangKeluar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangKeluar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barangKeluar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCari7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(barangKeluar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        mainPanel.add(barangKeluar1, "card2");

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel13.setText("Data Barang Keluar");

        btnTambah2.setBackground(new java.awt.Color(153, 255, 0));
        btnTambah2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTambah2.setForeground(new java.awt.Color(0, 0, 0));
        btnTambah2.setText("TAMBAH");
        btnTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah2ActionPerformed(evt);
            }
        });

        btnHapus2.setBackground(new java.awt.Color(153, 255, 0));
        btnHapus2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnHapus2.setForeground(new java.awt.Color(0, 0, 0));
        btnHapus2.setText("HAPUS");

        tblBK.setBackground(new java.awt.Color(204, 255, 204));
        tblBK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblBK);

        txtCari6.setText("Pencarian");
        txtCari6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCari6txtCari2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel18.setText("Detail");

        tblDetailBarangKeluar.setBackground(new java.awt.Color(204, 255, 204));
        tblDetailBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tblDetailBarangKeluar);

        btnCetak7.setBackground(new java.awt.Color(153, 255, 0));
        btnCetak7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnCetak7.setForeground(new java.awt.Color(0, 0, 0));
        btnCetak7.setText("UBAH");

        javax.swing.GroupLayout detBarangKeluarLayout = new javax.swing.GroupLayout(detBarangKeluar);
        detBarangKeluar.setLayout(detBarangKeluarLayout);
        detBarangKeluarLayout.setHorizontalGroup(
            detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detBarangKeluarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detBarangKeluarLayout.createSequentialGroup()
                        .addGroup(detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(detBarangKeluarLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(696, 696, 696)
                                    .addComponent(txtCari6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                                    .addComponent(jScrollPane9)))
                            .addGroup(detBarangKeluarLayout.createSequentialGroup()
                                .addComponent(btnTambah2)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus2)
                                .addGap(18, 18, 18)
                                .addComponent(btnCetak7)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        detBarangKeluarLayout.setVerticalGroup(
            detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCari6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detBarangKeluarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(detBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCetak7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(detBarangKeluarLayout.createSequentialGroup()
                        .addComponent(btnTambah2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(detBarangKeluar, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtCari6txtCari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCari6txtCari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCari6txtCari2ActionPerformed

    private void txtCari7txtCari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCari7txtCari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCari7txtCari2ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTambah2ActionPerformed

    private void tblBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBarangKeluarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barangKeluar1;
    private javax.swing.JButton btnCetak7;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus2;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah2;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel detBarangKeluar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tblBK;
    private javax.swing.JTable tblBarangKeluar;
    private javax.swing.JTable tblDetailBarangKeluar;
    private javax.swing.JTextField txtCari6;
    private javax.swing.JTextField txtCari7;
    // End of variables declaration//GEN-END:variables
}
