/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import Class.koneksi;
import java.awt.CardLayout;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author asus
 */
public class barang_Masuk extends javax.swing.JPanel {

    /**
     * Creates new form barang_Masuk
     */
    public barang_Masuk() {
        initComponents();
        mainPanel.setLayout(new CardLayout());
        
        mainPanel.add(dataBarangMasuk, "Data Barang Masuk");
        mainPanel.add(detailBarangMasuk, "Detail Barang Masuk");
        mainPanel.add(tambahBarangMasuk, "Tambah Barang Masuk");
        load_table_dataBarangMasuk();
    }
    
    private class Model_dataBarangMasuk{
    private Connection cn;
    public Model_dataBarangMasuk(){
       cn = new koneksi().konek();
    }
    
    //ambil semua data barang masuk
    public ResultSet tampilTambah() throws SQLException{
        String sql = "SELECT * FROM barangmasuk";
        PreparedStatement ps = cn.prepareStatement(sql);
        return ps.executeQuery();
    }


    //simpan data baru
    public void tambahData(int noMasuk, int idUser, String tanggalMasuk, int totalMasuk)throws SQLException{
        String sql = "INSERT INTO barangMasuk(no_masuk, id_user, tanggal_masuk, total_masuk)VALUES(?,?,?,?)";
        PreparedStatement ps = cn.prepareStatement(sql);

        ps.setInt(1, noMasuk);
        ps.setInt(2, idUser);
        ps.setString(3, tanggalMasuk);
        ps.setInt(4, totalMasuk);
        ps.executeUpdate();
        ps.close();
    }
}
    
    private void tampilDataBarangMasuk(){
        mainPanel.removeAll();
        mainPanel.add(dataBarangMasuk);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        btnTambah.setVisible(true);
        btnUbah.setVisible(true);
        btnHapus.setVisible(true);

        
        load_table_dataBarangMasuk();
    }
    
    private void tampilDetailBarangMasuk(){
        mainPanel.removeAll();
        mainPanel.add(detailBarangMasuk);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        btnUbahDetailBarangMasuk.setVisible(true);
        btnTambahDetailBarang.setVisible(true);
        btnSimpanDetailBarangMasuk.setVisible(true);
        
        load_table_dataBarangMasuk();
    }
    
    private void tampilTambahBarangMasuk() {
        mainPanel.removeAll();
        mainPanel.add(tambahBarangMasuk);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        btnSimpanTambah.setVisible(true);
        btnBatalTambah.setVisible(true);
    }
    
    private void load_table_dataBarangMasuk(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No Masuk");
        model.addColumn("Id User");
        model.addColumn("Tanggal Masuk");
        model.addColumn("Total Masuk");
        
        try {
            //membuat objek user dan mengambil data dari database
            Model_dataBarangMasuk dbm = new Model_dataBarangMasuk();
            ResultSet result =  dbm.tampilTambah();
            //loop data baris per baris
            while (result.next()){
                //Tambahkan baris ke dalam tabel model
            model.addRow(new Object[]{
                 result.getInt("no_masuk"),
                 result.getInt("id_user"),
                 result.getString("tanggal_masuk"),
                 result.getInt("total_masuk")
            });
        }
           //set model ke JTable
        tblDataBarangMasuk.setModel(model);
        tblDetailBarangMasuk.setModel(model);
        tblDetailBarangMasuk2.setModel(model);
        
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }       
    void reset(){
        tNoMasuk.setText(null);
        tIdUser.setText(null);
        tTglMasuk.setText(null);
        tTotalMasuk.setText(null);
    }
    /**z
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarangMasuk = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        btnUbah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDataBarangMasuk = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        detailBarangMasuk = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnTambahDetailBarang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDetailBarangMasuk = new javax.swing.JTable();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDetailBarangMasuk2 = new javax.swing.JTable();
        btnUbahDetailBarangMasuk = new javax.swing.JButton();
        btnSimpanDetailBarangMasuk = new javax.swing.JButton();
        tambahBarangMasuk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        btnSimpanTambah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tNoMasuk = new javax.swing.JTextField();
        tIdUser = new javax.swing.JTextField();
        tTglMasuk = new javax.swing.JTextField();
        tTotalMasuk = new javax.swing.JTextField();
        btnBatalTambah = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel3.setText("Data Barang Masuk");

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        btnUbah.setBackground(new java.awt.Color(0, 153, 0));
        btnUbah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        tblDataBarangMasuk.setBackground(new java.awt.Color(204, 255, 204));
        tblDataBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDataBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataBarangMasukMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDataBarangMasuk);

        btnHapus.setBackground(new java.awt.Color(0, 153, 0));
        btnHapus.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(0, 153, 0));
        btnTambah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangMasukLayout = new javax.swing.GroupLayout(dataBarangMasuk);
        dataBarangMasuk.setLayout(dataBarangMasukLayout);
        dataBarangMasukLayout.setHorizontalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangMasukLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnTambah)
                .addGap(35, 35, 35)
                .addComponent(btnUbah)
                .addGap(35, 35, 35)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(122, 122, 122)
                .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(dataBarangMasukLayout.createSequentialGroup()
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangMasukLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataBarangMasukLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        dataBarangMasukLayout.setVerticalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangMasukLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(16, 16, 16))
                    .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHapus)
                        .addComponent(btnTambah)
                        .addComponent(btnUbah)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        mainPanel.add(dataBarangMasuk, "card2");

        detailBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailBarangMasukMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel6.setText("Data Barang Masuk");

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        btnTambahDetailBarang.setBackground(new java.awt.Color(153, 255, 0));
        btnTambahDetailBarang.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTambahDetailBarang.setText("TAMBAH");
        btnTambahDetailBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDetailBarangActionPerformed(evt);
            }
        });

        tblDetailBarangMasuk.setBackground(new java.awt.Color(204, 255, 204));
        tblDetailBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetailBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailBarangMasukMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDetailBarangMasuk);

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel11.setText("Detail Barang Masuk");

        tblDetailBarangMasuk2.setBackground(new java.awt.Color(204, 255, 204));
        tblDetailBarangMasuk2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetailBarangMasuk2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailBarangMasuk2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblDetailBarangMasuk2);

        btnUbahDetailBarangMasuk.setBackground(new java.awt.Color(153, 255, 0));
        btnUbahDetailBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnUbahDetailBarangMasuk.setText("UBAH");

        btnSimpanDetailBarangMasuk.setBackground(new java.awt.Color(153, 255, 0));
        btnSimpanDetailBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnSimpanDetailBarangMasuk.setText("SIMPAN");

        javax.swing.GroupLayout detailBarangMasukLayout = new javax.swing.GroupLayout(detailBarangMasuk);
        detailBarangMasuk.setLayout(detailBarangMasukLayout);
        detailBarangMasukLayout.setHorizontalGroup(
            detailBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailBarangMasukLayout.createSequentialGroup()
                .addGroup(detailBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(detailBarangMasukLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(detailBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailBarangMasukLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(detailBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailBarangMasukLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(detailBarangMasukLayout.createSequentialGroup()
                                .addComponent(btnTambahDetailBarang)
                                .addGap(39, 39, 39)
                                .addComponent(btnUbahDetailBarangMasuk)
                                .addGap(42, 42, 42)
                                .addComponent(btnSimpanDetailBarangMasuk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(5, 5, 5))))
                    .addGroup(detailBarangMasukLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(detailBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(detailBarangMasukLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailBarangMasukLayout.setVerticalGroup(
            detailBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailBarangMasukLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(detailBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(detailBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambahDetailBarang)
                        .addComponent(btnUbahDetailBarangMasuk)
                        .addComponent(btnSimpanDetailBarangMasuk)))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        mainPanel.add(detailBarangMasuk, "card3");

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel8.setText("Tambah Barang Masuk");

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        btnSimpanTambah.setBackground(new java.awt.Color(153, 255, 0));
        btnSimpanTambah.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnSimpanTambah.setText("SIMPAN");
        btnSimpanTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanTambahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("No Masuk");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID User");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tanggal  Masuk");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Total Masuk");

        tNoMasuk.setText("jTextField1");

        tIdUser.setText("jTextField1");

        tTglMasuk.setText("jTextField1");

        tTotalMasuk.setText("jTextField1");

        btnBatalTambah.setBackground(new java.awt.Color(153, 255, 0));
        btnBatalTambah.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBatalTambah.setText("BATAL");
        btnBatalTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahBarangMasukLayout = new javax.swing.GroupLayout(tambahBarangMasuk);
        tambahBarangMasuk.setLayout(tambahBarangMasukLayout);
        tambahBarangMasukLayout.setHorizontalGroup(
            tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(863, Short.MAX_VALUE))
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                                .addComponent(btnSimpanTambah)
                                .addGap(42, 42, 42)
                                .addComponent(btnBatalTambah))
                            .addComponent(tNoMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                            .addComponent(tIdUser)
                            .addComponent(tTglMasuk)
                            .addComponent(tTotalMasuk))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        tambahBarangMasukLayout.setVerticalGroup(
            tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanTambah)
                    .addComponent(btnBatalTambah))
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNoMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(tTotalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        mainPanel.add(tambahBarangMasuk, "card4");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahDetailBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDetailBarangActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "Data Barang Masuk");
    }//GEN-LAST:event_btnTambahDetailBarangActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "Tambah Barang Masuk");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void detailBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailBarangMasukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_detailBarangMasukMouseClicked

    private void tblDataBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataBarangMasukMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "Detail Barang Masuk");
    }//GEN-LAST:event_tblDataBarangMasukMouseClicked

    private void tblDetailBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailBarangMasukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDetailBarangMasukMouseClicked

    private void tblDetailBarangMasuk2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailBarangMasuk2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDetailBarangMasuk2MouseClicked

    private void btnBatalTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalTambahActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBatalTambahActionPerformed

    private void btnSimpanTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanTambahActionPerformed
        // TODO add your handling code here:
    try {
        int noMasuk = Integer.parseInt(tNoMasuk.getText());
        int idUser = Integer.parseInt(tIdUser.getText());
        String tanggalMasuk = tTglMasuk.getText();
        int totalMasuk = Integer.parseInt(tTotalMasuk.getText());

        Model_dataBarangMasuk db = new Model_dataBarangMasuk();
        db.tambahData(noMasuk, idUser, tanggalMasuk, totalMasuk);

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        reset();
        load_table_dataBarangMasuk();
        tampilDataBarangMasuk();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSimpanTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "Tambah Barang Masuk");
    }//GEN-LAST:event_btnTambahActionPerformed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new panel.dataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalTambah;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpanDetailBarangMasuk;
    private javax.swing.JButton btnSimpanTambah;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambahDetailBarang;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUbahDetailBarangMasuk;
    private javax.swing.JPanel dataBarangMasuk;
    private javax.swing.JPanel detailBarangMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tIdUser;
    private javax.swing.JTextField tNoMasuk;
    private javax.swing.JTextField tTglMasuk;
    private javax.swing.JTextField tTotalMasuk;
    private javax.swing.JPanel tambahBarangMasuk;
    private javax.swing.JTable tblDataBarangMasuk;
    private javax.swing.JTable tblDetailBarangMasuk;
    private javax.swing.JTable tblDetailBarangMasuk2;
    // End of variables declaration//GEN-END:variables

}