/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import Class.koneksi;
import Class.Model_JenisBarang;
import static com.formdev.flatlaf.extras.components.FlatTabbedPane.TabType.card;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import javax.swing.JTable;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;





/**
 *
 * @author asus
 */
public class jenis_Barang extends javax.swing.JPanel {
       
    
    CardLayout card;
    
    //variabel untuk UBAH data jenis
    String kodeEdit = "";
    String namaEdit = "";
    
    
    /**
     * Creates new form jenis_Barang
     */
    public jenis_Barang() {
        initComponents();
        
        
        showDataJenis();
        load_table_jenis();

    }
    
    private void showDataJenis() { //menampilkan panel utama dengan button TAMBAH
        mainPanel.removeAll();
        mainPanel.add(dataJenis);
        mainPanel.repaint();
        mainPanel.revalidate();

        
        btnTambah.setVisible(true);
        btnUbah.setVisible(true);
        btnHapus.setVisible(true);
        
        load_table_jenis();
        
    }
    
    private void showTambahJenis() { //menampilkan panel untuk input tambah jenis
        mainPanel.removeAll();
        mainPanel.add(tambahJenis);
        mainPanel.repaint();
        mainPanel.revalidate();

        reset();
    }
    
     void load_table_jenis(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Jenis");
        model.addColumn("Nama Jenis");
        
        try {
            //membuat objek user dan mengambil data dari database
            Model_JenisBarang jns = new Model_JenisBarang();
            ResultSet rs =  jns.TampilJenis();
            //loop data baris per baris
            while (rs.next()){
                int kode = rs.getInt("kode_jenis");
                String kodeTampil = "JN" + String.format("%02d", kode);
                //Tambahkan baris ke dalam tabel model
            model.addRow(new Object[]{
                 kodeTampil,
                 rs.getString("nama_jenis"),
                  });
        }
           //set model ke JTable
        tblDataJenis.setModel(model);
        
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

     private void reset(){
        tKodeJenis.setText("");
        tNamaJenis.setText("");

        btnSimpan.setText("Simpan");
        
    }

    
     
    private void eventTableClick(){ //untuk menampilkan panel UBAH,HAPUS,BATAL saat salah satu data pada JTable diklik 
        tblDataJenis.addMouseListener(new MouseAdapter(){
        @Override
        public void mouseClicked(MouseEvent e){
            int baris = tblDataJenis.getSelectedRow();
            
            if (baris != -1){
                //ambil data dari tabel
                String kode = tblDataJenis.getValueAt(baris, 0).toString();
                String nama = tblDataJenis.getValueAt(baris, 1).toString();
                
                
                kodeEdit = kode; //simpan data kevariabel
                namaEdit = nama;
        }
        }
        });
    }
     
    
    public void autoKodeJenis(){
        Model_JenisBarang jns = new Model_JenisBarang();
        ResultSet rs = jns.autoKodeJenis();
        try {
            if(rs.next()){
                int kode = rs.getInt("kode_jenis") + 1; // cukup +1
                tKodeJenis.setText("JN" + String.format("%02d", kode));
            } else {
                tKodeJenis.setText("JN01");
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "gagal : " + e.getMessage());
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is \always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataJenis = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDataJenis = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tambahJenis = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tKodeJenis = new javax.swing.JTextField();
        tNamaJenis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        mainPanel.setLayout(null);

        dataJenis.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel5.setText("Data Jenis Barang");
        dataJenis.add(jLabel5);
        jLabel5.setBounds(30, 30, 142, 21);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        dataJenis.add(jSeparator5);
        jSeparator5.setBounds(31, 56, 970, 3);
        dataJenis.add(jLabel6);
        jLabel6.setBounds(997, 108, 0, 0);

        tblDataJenis.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        tblDataJenis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDataJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataJenisMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDataJenis);

        dataJenis.add(jScrollPane3);
        jScrollPane3.setBounds(64, 146, 910, 390);

        btnTambah.setBackground(new java.awt.Color(0, 153, 0));
        btnTambah.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        dataJenis.add(btnTambah);
        btnTambah.setBounds(60, 100, 80, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-22.png"))); // NOI18N
        dataJenis.add(jLabel7);
        jLabel7.setBounds(940, 100, 30, 30);

        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });
        dataJenis.add(tCari);
        tCari.setBounds(710, 100, 260, 30);

        btnUbah.setBackground(new java.awt.Color(0, 153, 0));
        btnUbah.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        dataJenis.add(btnUbah);
        btnUbah.setBounds(170, 100, 72, 30);

        btnHapus.setBackground(new java.awt.Color(0, 153, 0));
        btnHapus.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        dataJenis.add(btnHapus);
        btnHapus.setBounds(350, 110, 72, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_panel (1).png"))); // NOI18N
        dataJenis.add(jLabel4);
        jLabel4.setBounds(0, 0, 1050, 580);

        mainPanel.add(dataJenis);
        dataJenis.setBounds(0, 0, 1050, 580);

        tambahJenis.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel17.setText("Tambah Jenis Barang");
        tambahJenis.add(jLabel17);
        jLabel17.setBounds(36, 35, 168, 21);

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        tambahJenis.add(jSeparator17);
        jSeparator17.setBounds(36, 62, 930, 3);
        tambahJenis.add(jLabel18);
        jLabel18.setBounds(997, 94, 0, 0);

        btnSimpan.setBackground(new java.awt.Color(0, 153, 0));
        btnSimpan.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        tambahJenis.add(btnSimpan);
        btnSimpan.setBounds(860, 460, 80, 30);

        btnBatal.setFont(new java.awt.Font("Franklin Gothic Book", 1, 13)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        tambahJenis.add(btnBatal);
        btnBatal.setBounds(760, 460, 72, 30);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Jenis");
        tambahJenis.add(jLabel1);
        jLabel1.setBounds(100, 200, 100, 21);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Jenis");
        tambahJenis.add(jLabel2);
        jLabel2.setBounds(100, 310, 110, 20);

        tKodeJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKodeJenisMouseClicked(evt);
            }
        });
        tKodeJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKodeJenisActionPerformed(evt);
            }
        });
        tambahJenis.add(tKodeJenis);
        tKodeJenis.setBounds(100, 230, 840, 40);
        tambahJenis.add(tNamaJenis);
        tNamaJenis.setBounds(100, 340, 840, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_panel (1).png"))); // NOI18N
        tambahJenis.add(jLabel3);
        jLabel3.setBounds(0, 0, 1050, 580);

        mainPanel.add(tambahJenis);
        tambahJenis.setBounds(0, 0, 1050, 580);

        add(mainPanel);
        mainPanel.setBounds(0, 0, 1050, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        showTambahJenis();
        autoKodeJenis();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        Model_JenisBarang jns = new Model_JenisBarang();
        String kodeInput = tKodeJenis.getText();
        String namaInput = tNamaJenis.getText();

        // Validasi input kosong
        if (namaInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Jenis tidak boleh kosong!");
            return;
        }

        if (btnSimpan.getText().equals("Ubah")) {
            // Logika UBAH: Gunakan kodeEdit (kode asli dari database)
            // Jika kodeEdit berisi "JN03", ambil angka "03" atau sesuai kebutuhan DB
            String kodeUntukDB = kodeEdit.replace("JN", ""); 
            jns.setKode_jenis(kodeUntukDB);
            jns.setNama_jenis(namaInput);
            jns.UbahJenis();
        } else {
            // Logika SIMPAN BARU: Ambil angka saja dari "JN01"
            if (kodeInput.length() >= 2) {
                String kodeAngka = kodeInput.substring(2);
                jns.setKode_jenis(kodeAngka);
                jns.setNama_jenis(namaInput);
                jns.TambahJenis();
            } else {
                JOptionPane.showMessageDialog(this, "Format Kode Salah!");
                return;
            }
        }
        load_table_jenis();
        showDataJenis(); //kembali ke panel tampilJenis
           
       
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showDataJenis();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tblDataJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataJenisMouseClicked
        int baris = tblDataJenis.getSelectedRow();
        
        if (baris != -1){
            String kode = tblDataJenis.getValueAt(baris, 0).toString();
            String nama = tblDataJenis.getValueAt(baris, 1).toString();
           
            
            tKodeJenis.setText(kode);
            tKodeJenis.setEditable(false);
            tNamaJenis.setText(nama);
        }
    }//GEN-LAST:event_tblDataJenisMouseClicked

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased

        String cari = tCari.getText();
        
        DefaultTableModel model = (DefaultTableModel) tblDataJenis.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "SELECT * FROM jenisbarang WHERE kode_jenis LIKE ? OR nama_jenis LIKE ?";
            PreparedStatement ps = koneksi.configDB().prepareStatement(sql);
            ps.setString(1, "%" + cari + "%");
            ps.setString(2, "%" + cari + "%");
            
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
            int kode = rs.getInt("kode_jenis"); // AMBIL INT
            String kodeTampil = "JN" + String.format("%02d", kode); // FORMAT

            model.addRow(new Object[]{
                kodeTampil,
                rs.getString("nama_jenis")
            });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_tCariKeyReleased

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
       
    }//GEN-LAST:event_tCariActionPerformed

    private void tKodeJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKodeJenisMouseClicked
        autoKodeJenis();
    }//GEN-LAST:event_tKodeJenisMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
         // pastikan ada baris yang dipilih
    int row = tblDataJenis.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan diubah!");
        return;
    }
    // ambil data dari tabel
    eventTableClick();
    showTambahJenis();

    tKodeJenis.setText(kodeEdit);
    tKodeJenis.setEditable(false);
    tNamaJenis.setText(namaEdit);

    btnSimpan.setText("Ubah");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       Model_JenisBarang jns = new Model_JenisBarang();
       String kodeAngka = tKodeJenis.getText().substring(2);
       jns.setKode_jenis(kodeAngka);
       
       jns.HapusJenis();
       load_table_jenis();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tKodeJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKodeJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKodeJenisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel dataJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tKodeJenis;
    private javax.swing.JTextField tNamaJenis;
    private javax.swing.JPanel tambahJenis;
    private javax.swing.JTable tblDataJenis;
    // End of variables declaration//GEN-END:variables
}
