/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import Class.koneksi;
import Class.Model_JenisBarang;
import static com.formdev.flatlaf.extras.components.FlatTabbedPane.TabType.card;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Statement;
import javax.swing.JTable;





/**
 *
 * @author asus
 */
public class jenis_Barang extends javax.swing.JPanel {
       
    
    CardLayout card;
    
    //variabel untuk UBAH data jenis
    String kodeEdit = null;
    
    
    /**
     * Creates new form jenis_Barang
     */
    public jenis_Barang() {
        initComponents();
        
        card = (CardLayout) mainPanel.getLayout(); 
        showTampilJenis();
        eventTableClick();
    }
    
    private void showTampilJenis() { //menampilkan panel utama dengan button TAMBAH
        mainPanel.removeAll();
        mainPanel.add(tampilJenis);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        btnTambah.setVisible(true);
        btnUbah.setVisible(true);
        btnHapus.setVisible(true);
        
        load_table_jenis();
        
    }
    
    private void showTambahJenis() { //menampilkan panel untuk input tambah jenis
        mainPanel.removeAll();
        mainPanel.add(tambahJenis);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        reset();
    }
    
     void load_table_jenis(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Jenis");
        model.addColumn("Nama Jenis");
        
        try {
            //membuat objek user dan mengambil data dari database
            Model_JenisBarang jns = new Model_JenisBarang();
            ResultSet result =  jns.TampilJenis();
            //loop data baris per baris
            while (result.next()){
                //Tambahkan baris ke dalam tabel model
            model.addRow(new Object[]{
                 result.getString("kode_jenis"),
                 result.getString("nama_jenis"),
                  });
        }
           //set model ke JTable
        tblTampilJenis.setModel(model);
        
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

     private void reset(){
        tKodeJenis.setText("");
        tNamaJenis.setText("");

        btnSimpan.setText("Simpan");
        
    }

    
     
    private void eventTableClick(){ //untuk menampilkan panel UBAH,HAPUS,BATAL saat salah satu data pada JTable diklik 
        tblTampilJenis.addMouseListener(new MouseAdapter(){
        @Override
        public void mouseClicked(MouseEvent e){
            int baris = tblTampilJenis.getSelectedRow();
            
            if (baris != -1){
                //ambil data dari tabel
                String kode = tblTampilJenis.getValueAt(baris, 0).toString();
                String nama = tblTampilJenis.getValueAt(baris, 1).toString();
                
                
                kodeEdit = kode; //simpan kode untuk UBAH
                card.show(mainPanel, "dataJenis");//pindah ke panel dataJenis(UBAH,HAPUS,BATAL)
            }
        }
        });
    }
     
    
    
     
     void simpan(){
         
     }
     
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is \always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilJenis = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTampilJenis = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        tambahJenis = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tKodeJenis = new javax.swing.JTextField();
        tNamaJenis = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel5.setText("Data Jenis Barang");

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        tblTampilJenis.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        tblTampilJenis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTampilJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTampilJenisMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTampilJenis);

        btnTambah.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });
        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tCariKeyReleased(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tampilJenisLayout = new javax.swing.GroupLayout(tampilJenis);
        tampilJenis.setLayout(tampilJenisLayout);
        tampilJenisLayout.setHorizontalGroup(
            tampilJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilJenisLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(tampilJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilJenisLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(tampilJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(tampilJenisLayout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tampilJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(tCari, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(53, 53, 53))
        );
        tampilJenisLayout.setVerticalGroup(
            tampilJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilJenisLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGroup(tampilJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tampilJenisLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tampilJenisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tampilJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tampilJenisLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tampilJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTambah)
                                    .addComponent(btnUbah)
                                    .addComponent(btnHapus)))
                            .addGroup(tampilJenisLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        mainPanel.add(tampilJenis, "card9");

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        jLabel17.setText("Tambah Jenis Barang");

        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));

        btnSimpan.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel1.setText("Kode Jenis");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel2.setText("Nama Jenis");

        tKodeJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKodeJenisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tambahJenisLayout = new javax.swing.GroupLayout(tambahJenis);
        tambahJenis.setLayout(tambahJenisLayout);
        tambahJenisLayout.setHorizontalGroup(
            tambahJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahJenisLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(tambahJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahJenisLayout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(53, 53, 53))
                    .addGroup(tambahJenisLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(tambahJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(tambahJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(tKodeJenis, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                                .addComponent(tNamaJenis)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(tambahJenisLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(tambahJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        tambahJenisLayout.setVerticalGroup(
            tambahJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahJenisLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17)
                .addGroup(tambahJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahJenisLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel18))
                    .addGroup(tambahJenisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(tambahJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnBatal))))
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(tKodeJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(tNamaJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        mainPanel.add(tambahJenis, "card11");

        add(mainPanel, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        showTambahJenis();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       Model_JenisBarang jns = new Model_JenisBarang();
       jns.setKode_jenis(tKodeJenis.getText());
       jns.setNama_jenis(tNamaJenis.getText());
       
       jns.TambahJenis();
       load_table_jenis();
       showTampilJenis();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        showTampilJenis();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tblTampilJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTampilJenisMouseClicked
        int baris = tblTampilJenis.getSelectedRow();
        
        if (baris != -1){
            String kode = tblTampilJenis.getValueAt(baris, 0).toString();
            String nama = tblTampilJenis.getValueAt(baris, 1).toString();
           
            
            tKodeJenis.setText(kode);
            tKodeJenis.setEditable(false);
            tNamaJenis.setText(nama);
        }
    }//GEN-LAST:event_tblTampilJenisMouseClicked

    private void tCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyReleased
        
    }//GEN-LAST:event_tCariKeyReleased

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
       
    }//GEN-LAST:event_tCariActionPerformed

    private void tKodeJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKodeJenisMouseClicked
        
    }//GEN-LAST:event_tKodeJenisMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        Model_JenisBarang jns = new Model_JenisBarang();
        jns.setKode_jenis(tKodeJenis.getText());
        jns.setNama_jenis(tNamaJenis.getText());

        jns.UbahJenis();
        load_table_jenis();
        showTambahJenis();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        Model_JenisBarang jns = new Model_JenisBarang();
       jns.setKode_jenis(tKodeJenis.getText());
       
       jns.HapusJenis();
       load_table_jenis();
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField tCari;
    private javax.swing.JTextField tKodeJenis;
    private javax.swing.JTextField tNamaJenis;
    private javax.swing.JPanel tambahJenis;
    private javax.swing.JPanel tampilJenis;
    private javax.swing.JTable tblTampilJenis;
    // End of variables declaration//GEN-END:variables
}
