/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import Class.koneksi;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.PreparedStatement;
import frame.dashboard;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author user
 */
public class formLogin extends javax.swing.JFrame {

    private Object ex;

    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
    }
    
    void reset(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        tUsername = new custom.teksfield();
        tPassword = new custom.teksfield();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(0, 153, 0));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 217, 40));

        tUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tUsername.setText("username");
        tUsername.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        tUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-18.png"))); // NOI18N
        tUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tUsernameFocusLost(evt);
            }
        });
        tUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 217, 39));

        tPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tPassword.setText("password");
        tPassword.setFont(new java.awt.Font("Franklin Gothic Book", 0, 12)); // NOI18N
        tPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-password-18.png"))); // NOI18N
        tPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tPasswordFocusLost(evt);
            }
        });
        jPanel1.add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 217, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg login.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 556, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = tUsername.getText();
        String password = tPassword.getText();
        
        String sql = "SELECT * FROM user WHERE username = ? AND password = MD5(?)"; 
        Connection conn = new koneksi().configDB();
        
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                new dashboard().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Username atau Password salah!");
            }
        } catch (SQLException sQLException) {
            Logger.getLogger(formLogin.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsernameActionPerformed

    private void tUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusGained
        String username = tUsername.getText();
        if(username.equals("username")){
            tUsername.setText("");
        }
    }//GEN-LAST:event_tUsernameFocusGained

    private void tPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPasswordFocusGained
        String password = tPassword.getText();
        if(password.equals("password")){
            tPassword.setText("");
        }
    }//GEN-LAST:event_tPasswordFocusGained

    private void tPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPasswordFocusLost
        String password = tPassword.getText();
        if(password.equals("")||password.equals("password")){
            tPassword.setText("password");
        }
    }//GEN-LAST:event_tPasswordFocusLost

    private void tUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUsernameFocusLost
        String username = tUsername.getText();
        if(username.equals("")||username.equals("username")){
            tUsername.setText("username");
        }
    }//GEN-LAST:event_tUsernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private custom.teksfield tPassword;
    private custom.teksfield tUsername;
    // End of variables declaration//GEN-END:variables
}
