package frame;

import Class.Model_User;
import Class.Model_Login;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import panel.About;
import panel.barang_Keluar;
import panel.barang_Masuk;
//import panel.formBarang;
import panel.hasil_Panen;
import panel.jenis_Barang;
import panel.laporan;
import panel.logout;

/**
 *
 * @author user
 */
public class dashboard extends javax.swing.JFrame {
private javax.swing.JLabel jLabel1;

    
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        runningText();
        execute();
    }
    
    void runningText() {
        Timer timer = new Timer(100, new ActionListener() {
            int jumlahSpasi = 250;
            String spasi = " ".repeat(jumlahSpasi);
            String text = spasi + "Selamat datang di Aplikasi Inventory Pertanian AGRITECH. Aplikasi ini dirancang untuk membantu Anda mengelola setiap aspek persediaan pertanian secara lebih teratur, cepat, dan akurat. Dengan sistem yang modern dan mudah digunakan, Anda dapat memantau stok, mencatat transaksi, mengelola data produk, serta meningkatkan efisiensi dalam proses pengelolaan hasil pertanian.";

            @Override
            public void actionPerformed(ActionEvent e) {
                text = text.substring(1) + text.charAt(0);
                jLabel1.setText(text);
            }
        });
        timer.start();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        lAgritech = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        pn_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_navbar.setBackground(new java.awt.Color(0, 153, 0));
        pn_navbar.setMinimumSize(new java.awt.Dimension(100, 80));
        pn_navbar.setPreferredSize(new java.awt.Dimension(1300, 70));

        lAgritech.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAgritech.setForeground(new java.awt.Color(255, 255, 255));
        lAgritech.setText("A G R I T E C H ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat datang di Aplikasi Inventroy Pertanian");

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lAgritech)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAgritech)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(250, 580));
        pn_sidebar.setVerifyInputWhenFocusTarget(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_content.setBackground(new java.awt.Color(255, 255, 255));
        pn_content.setPreferredSize(new java.awt.Dimension(1200, 80));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);
        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        pn_utama.add(new content_bg());
        pn_utama.repaint();
        pn_utama.revalidate();     
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAgritech;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        // Memanggil icon menu
        ImageIcon iconDashboard = new ImageIcon(getClass().getResource("/img/iconDashboard.png"));
        ImageIcon iconData = new ImageIcon(getClass().getResource("/img/iconData.png"));
        ImageIcon iconKelola = new ImageIcon(getClass().getResource("/img/iconKelola.png"));
        ImageIcon iconLaporan = new ImageIcon(getClass().getResource("/img/iconLaporan.png"));
        ImageIcon iconAbout = new ImageIcon(getClass().getResource("/img/iconAbout.png"));
        ImageIcon iconLogout = new ImageIcon(getClass().getResource("/img/iconLogout.png"));
        
        // Memanggil icon sub menu
        ImageIcon iconBarang = new ImageIcon(getClass().getResource("/img/barang.png"));
        ImageIcon iconJenisBarang = new ImageIcon(getClass().getResource("/"));
        ImageIcon iconBarangMasuk = new ImageIcon(getClass().getResource("/"));
        ImageIcon iconBarangKeluar = new ImageIcon(getClass().getResource("/"));
        ImageIcon iconHasilPanen = new ImageIcon(getClass().getResource("/"));
        
        // Sub menu pada menu Data
        MenuItem menuBarang1 = new MenuItem(null, true, iconBarang, "Barang", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                //.add(new formBarang());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        } );
        
        MenuItem menuBarang2 = new MenuItem(null, true, iconBarang, "Jenis Barang", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new jenis_Barang());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        } );
        
        // Sub menu pada menu Kelola
        MenuItem menuKelola1 = new MenuItem(null, true, iconBarang, "Barang Masuk", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new barang_Masuk());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        } );
        
        MenuItem menuKelola2 = new MenuItem(null, true, iconBarang, "Barang Keluar", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new barang_Keluar());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        } );
        
        // Sub menu pada menu Laporan
        
        MenuItem menuLaporan1 = new MenuItem(null, true, iconBarang, "Barang Keluar", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new laporan());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        } );
      
        MenuItem menuLaporan2 = new MenuItem(null, true, iconBarang, "Barang Keluar", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new laporan());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        } );
        MenuItem menuLaporan3 = new MenuItem(null, true, iconBarang, "Hasil Panen", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new hasil_Panen());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        } );
        
        
        // Menu utama memanggil sub menu
        MenuItem menuDasbor = new MenuItem(iconDashboard, false, null, "Dashboard", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pn_utama.removeAll();
                pn_utama.add(new content_bg());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
        // Menu utama memanggil sub menu
        MenuItem menuAbout = new MenuItem(iconAbout, false, null, "About", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                pn_utama.removeAll();
                pn_utama.add(new About());
                pn_utama.repaint();
                pn_utama.revalidate();
            }
        });
        
         MenuItem menuLogout = new MenuItem(iconLogout, false, null, "Logout", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // 1. Tampilkan konfirmasi (Opsional tapi disarankan)
                int confirm = javax.swing.JOptionPane.showConfirmDialog(null, 
                        "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", 
                        javax.swing.JOptionPane.YES_NO_OPTION);

                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                   dispose();
                    new formLogin().setVisible(true); 
                }
    }
});
        

        
        // Menu utama memamnggil sub menu
        
        MenuItem menuData = new MenuItem(iconData, false, null, "Data", null, menuBarang1,menuBarang2);
        MenuItem menuKelola = new MenuItem(iconKelola, false, null, "Kelola", null, menuKelola1,menuKelola2);
        MenuItem menuLaporan = new MenuItem(iconLaporan, false, null, "Laporan", null, menuLaporan1, menuLaporan2, menuLaporan3);
  
        
        addMenu(menuDasbor, menuData, menuKelola, menuLaporan, menuAbout, menuLogout);     
    }
    
    private void addMenu(MenuItem... menu) {
        for (int i = 0; i < menu.length; i++) {
            pn_menu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        pn_menu.revalidate();
    }
}
